const funFacts: { [key: string]: string[] } = {
  en: [
    'Oldest Library: The oldest known library dates back to around 2600 BCE in Sumer, an ancient civilization in Mesopotamia.',
    'First Public Library: The Library of Ashurbanipal in Nineveh, Assyria (modern-day Iraq) was one of the first great libraries and was accessible to scholars and scribes around the 7th century BCE.',
    'Largest Library in the World: The Library of Congress in Washington, D.C. is the largest library in the world by collection size, housing over 170 million items.',
    "Most Expensive Book Ever Sold: The 'Codex Leicester,' a scientific manuscript by Leonardo da Vinci, was sold to Bill Gates in 1994 for $30.8 million.",
    "Longest Novel: 'In Search of Lost Time' by Marcel Proust holds the Guinness World Record for the longest novel, with about 1.2 million words.",
    'Book of Kells: This illuminated manuscript Gospel book in Latin, containing the four Gospels of the New Testament, was created by Celtic monks around 800 AD and is one of the most famous medieval manuscripts.',
    'Books in Braille: Louis Braille, who was blinded in an accident as a child, invented the Braille system of reading and writing for the blind in 1824, making literature accessible to visually impaired individuals.',
    'Most Translated Book: The Bible is the most translated book in the world, having been translated into over 3,000 languages.',
    "Fahrenheit 451: Ray Bradbury’s famous dystopian novel about a future where books are banned and 'firemen' burn any that are found, was written on a rented typewriter in the basement of UCLA’s Powell Library.",
    'Tiny Books: The smallest book in the world is a 0.07 mm x 0.10 mm (0.0028 in x 0.0039 in) copy of the New Testament of the King James Bible created by MIT’s Nano Structures Laboratory.',
    'The Bodleian Library: The Bodleian Library at the University of Oxford is one of the oldest libraries in Europe and has been in continuous operation since 1602.',
    'The Library Cat: Libraries sometimes have resident cats. One famous example was Dewey Readmore Books, who lived in the Spencer Public Library in Iowa for 19 years and even had a book written about him.',
    'Book-burning Libraries: In ancient China, Emperor Qin Shi Huang ordered the burning of many books to suppress intellectual discourse that opposed his rule around 213 BCE.',
    'Digital Libraries: Project Gutenberg, started in 1971 by Michael S. Hart, is the oldest digital library and offers over 60,000 free eBooks.',
    "Dr. Seuss’s Real Name: The famous children’s book author Dr. Seuss was born Theodor Seuss Geisel. He used the pen name 'Dr. Seuss,' his mother's maiden name.",
    'Library Ghosts: Some libraries are rumored to be haunted, like the Peoria Public Library in Illinois, which is said to be haunted by the ghost of its first librarian.',
    'Library Fine Records: The largest library fine ever paid was $345.14 by Emily Canellos-Simms, who returned a book to the Kewanee Public Library in Illinois 47 years late.',
    'Ancient Scrolls: The Library of Alexandria, one of the most famous libraries of the ancient world, housed an estimated 400,000 to 700,000 scrolls before it was destroyed.',
    'Books as Art: Some artists use books as their medium, creating sculptures by carving into them, like the works of Brian Dettmer, who creates intricate designs by cutting into old books.',
    'Public Lending Right: In some countries, authors receive payments from the government each time their books are borrowed from public libraries, known as Public Lending Right (PLR). This practice is common in the UK, Canada, and several European countries.',
  ],
  pl: [
    'Najstarsza biblioteka: Najstarsza znana biblioteka pochodzi z około 2600 roku p.n.e. w Sumerze, starożytnej cywilizacji w Mezopotamii.',
    'Pierwsza biblioteka publiczna: Biblioteka Aszurbanipala w Niniwie, Asyria (dzisiejszy Irak) była jedną z pierwszych wielkich bibliotek i była dostępna dla uczonych i skrybów około VII wieku p.n.e.',
    'Największa biblioteka na świecie: Biblioteka Kongresu w Waszyngtonie, D.C. jest największą biblioteką na świecie pod względem wielkości zbiorów, posiadającą ponad 170 milionów pozycji.',
    "Najdroższa książka, jaka kiedykolwiek sprzedano: 'Codex Leicester,' rękopis naukowy Leonarda da Vinci, został sprzedany Billowi Gatesowi w 1994 roku za 30,8 milionów dolarów.",
    "Najdłuższa powieść: 'W poszukiwaniu straconego czasu' Marcela Prousta posiada rekord Guinnessa na najdłuższą powieść, z około 1,2 miliona słów.",
    'Księga z Kells: Ta iluminowana rękopiśmienna księga ewangelii w języku łacińskim, zawierająca cztery Ewangelie Nowego Testamentu, została stworzona przez celtyckich mnichów około 800 roku n.e. i jest jedną z najsłynniejszych średniowiecznych manuskryptów.',
    'Książki w brajlu: Louis Braille, który jako dziecko stracił wzrok w wyniku wypadku, wynalazł system czytania i pisania dla niewidomych w 1824 roku, umożliwiając dostęp do literatury dla osób niewidomych.',
    'Najbardziej tłumaczona książka: Biblia jest najbardziej tłumaczoną książką na świecie, przetłumaczoną na ponad 3000 języków.',
    "Fahrenheit 451: Słynna dystopijna powieść Raya Bradbury'ego o przyszłości, w której książki są zakazane, a 'strażacy' palą wszystkie znalezione egzemplarze, została napisana na wynajętej maszynie do pisania w piwnicy biblioteki Powella na UCLA.",
    'Maleńkie książki: Najmniejsza książka na świecie to 0,07 mm x 0,10 mm (0,0028 cala x 0,0039 cala) kopia Nowego Testamentu Biblii Króla Jakuba stworzona przez Nano Structures Laboratory MIT.',
    'Biblioteka Bodleian: Biblioteka Bodleian na Uniwersytecie Oksfordzkim jest jedną z najstarszych bibliotek w Europie i działa nieprzerwanie od 1602 roku.',
    'Kot biblioteczny: Biblioteki czasami mają rezydentne koty. Jednym z słynnych przykładów był Dewey Readmore Books, który mieszkał w Spencer Public Library w Iowa przez 19 lat i nawet doczekał się książki napisanej o nim.',
    'Biblioteki palenia książek: W starożytnych Chinach, cesarz Qin Shi Huang nakazał spalenie wielu książek, aby stłumić intelektualne dyskusje, które sprzeciwiały się jego rządom, około 213 roku p.n.e.',
    'Biblioteki cyfrowe: Projekt Gutenberg, rozpoczęty w 1971 roku przez Michaela S. Harta, jest najstarszą biblioteką cyfrową i oferuje ponad 60 000 darmowych e-booków.',
    "Prawdziwe nazwisko Dr. Seussa: Słynny autor książek dla dzieci Dr. Seuss urodził się jako Theodor Seuss Geisel. Używał pseudonimu 'Dr. Seuss,' nazwiska panieńskiego swojej matki.",
    'Duchy biblioteczne: Niektóre biblioteki są podobno nawiedzone, jak Peoria Public Library w Illinois, która podobno jest nawiedzana przez ducha swojego pierwszego bibliotekarza.',
    'Rekordowe opłaty biblioteczne: Największą opłatę biblioteczną w historii wyniosła Emily Canellos-Simms, która zwróciła książkę do Kewanee Public Library w Illinois 47 lat po terminie, płacąc 345,14 dolarów.',
    'Starożytne zwoje: Biblioteka Aleksandryjska, jedna z najsłynniejszych bibliotek starożytnego świata, posiadała od 400 000 do 700 000 zwojów przed jej zniszczeniem.',
    'Książki jako sztuka: Niektórzy artyści używają książek jako medium, tworząc rzeźby poprzez wycinanie ich, jak dzieła Briana Dettmera, który tworzy skomplikowane wzory, wycinając stare książki.',
    'Prawo do wypożyczania publicznego: W niektórych krajach autorzy otrzymują wynagrodzenie od rządu za każdym razem, gdy ich książki są wypożyczane z bibliotek publicznych, znane jako Prawo do Wypożyczania Publicznego (PLR). Ta praktyka jest powszechna w Wielkiej Brytanii, Kanadzie i kilku krajach europejskich.',
  ],
  it: [
    "Biblioteca più antica: La biblioteca più antica conosciuta risale al 2600 a.C. a Sumer, un'antica civiltà della Mesopotamia.",
    "Prima biblioteca pubblica: La Biblioteca di Assurbanipal a Ninive, Assiria (l'odierno Iraq) fu una delle prime grandi biblioteche ed era accessibile a studiosi e scribi intorno al VII secolo a.C.",
    'Biblioteca più grande del mondo: La Biblioteca del Congresso a Washington, D.C. è la più grande biblioteca del mondo per dimensioni della collezione, ospitando oltre 170 milioni di articoli.',
    "Libro più costoso mai venduto: Il 'Codex Leicester,' un manoscritto scientifico di Leonardo da Vinci, fu venduto a Bill Gates nel 1994 per 30,8 milioni di dollari.",
    "Romanzo più lungo: 'Alla ricerca del tempo perduto' di Marcel Proust detiene il Guinness World Record per il romanzo più lungo, con circa 1,2 milioni di parole.",
    "Libro di Kells: Questo manoscritto evangelico illustrato in latino, contenente i quattro Vangeli del Nuovo Testamento, fu creato dai monaci celtici intorno all'800 d.C. ed è uno dei manoscritti medievali più famosi.",
    'Libri in braille: Louis Braille, che rimase cieco a seguito di un incidente da bambino, inventò il sistema di lettura e scrittura per i ciechi nel 1824, rendendo la letteratura accessibile ai non vedenti.',
    'Libro più tradotto: La Bibbia è il libro più tradotto al mondo, essendo stata tradotta in oltre 3000 lingue.',
    "Fahrenheit 451: Il famoso romanzo distopico di Ray Bradbury su un futuro in cui i libri sono vietati e i 'vigili del fuoco' bruciano tutti quelli trovati, fu scritto su una macchina da scrivere a noleggio nel seminterrato della biblioteca Powell dell'UCLA.",
    'Libri minuscoli: Il libro più piccolo del mondo è una copia del Nuovo Testamento della Bibbia di Re Giacomo di 0,07 mm x 0,10 mm (0,0028 in x 0,0039 in) creata dal Nano Structures Laboratory del MIT.',
    "Biblioteca Bodleian: La Biblioteca Bodleian presso l'Università di Oxford è una delle biblioteche più antiche d'Europa ed è in funzione continua dal 1602.",
    'Il gatto della biblioteca: Le biblioteche a volte ospitano gatti residenti. Un esempio famoso è stato Dewey Readmore Books, che visse nella Spencer Public Library in Iowa per 19 anni e persino ha avuto un libro scritto su di lui.',
    "Biblioteche di roghi di libri: Nell'antica Cina, l'imperatore Qin Shi Huang ordinò la combustione di molti libri per sopprimere il discorso intellettuale che si opponeva al suo dominio intorno al 213 a.C.",
    'Biblioteche digitali: Il Progetto Gutenberg, iniziato nel 1971 da Michael S. Hart, è la più antica biblioteca digitale e offre oltre 60.000 eBook gratuiti.',
    "Vero nome del Dr. Seuss: Il famoso autore di libri per bambini Dr. Seuss nacque Theodor Seuss Geisel. Usava lo pseudonimo 'Dr. Seuss,' il cognome da nubile di sua madre.",
    'Fantasmi della biblioteca: Alcune biblioteche sono presumibilmente infestate, come la Peoria Public Library in Illinois, che si dice sia infestata dal fantasma del suo primo bibliotecario.',
    'Record di multe bibliotecarie: La più grande multa bibliotecaria mai pagata è stata di 345,14 dollari da Emily Canellos-Simms, che ha restituito un libro alla Kewanee Public Library in Illinois con 47 anni di ritardo.',
    'Antichi rotoli: La Biblioteca di Alessandria, una delle biblioteche più famose del mondo antico, conteneva da 400.000 a 700.000 rotoli prima della sua distruzione.',
    'Libri come arte: Alcuni artisti usano i libri come mezzo, creando sculture intagliandoli, come le opere di Brian Dettmer, che crea disegni intricati intagliando vecchi libri.',
    'Diritto di prestito pubblico: In alcuni paesi, gli autori ricevono pagamenti dal governo ogni volta che i loro libri vengono presi in prestito dalle biblioteche pubbliche, noto come Diritto di Prestito Pubblico (PLR). Questa pratica è comune nel Regno Unito, in Canada e in diversi paesi europei.',
  ],
};

export default funFacts;
